services:
  - type: web
    name: chatapp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString

  - type: static
    name: chatapp-frontend
    buildCommand: echo "Static site build"
    staticPublishPath: ./frontend
    envVars:
      - key: BACKEND_URL
        value: https://chatapp-backend.onrender.com

databases:
  - name: chatapp-db
    databaseName: chatapp
    plan: free 